name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'

      - name: Install Dart SDK
        run: sudo apt-get update && sudo apt-get install -y apt-transport-https && \
          sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -' && \
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list' && \
          sudo apt-get update && sudo apt-get install -y dart && \
          echo "export PATH=\"$PATH:/usr/lib/dart/bin\"" >> $GITHUB_ENV

      - name: Install dependencies
        run: flutter pub get

      - name: Run analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release